// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sivhlbxcqdyvzbntyrhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdmhsYnhjcWR5dnpibnR5cmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjMwOTYsImV4cCI6MjA2NTgzOTA5Nn0._CDA0hWkcgA4w0QPD8tO6kLmpuLYEBka8qwQDOgsHu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);